language: php
sudo: false
addons:
  apt:
    packages:
    - poppler-utils
php:
  - 5.5
  - 5.6
  - 7.0
before_script:
 - composer install -vvv
script:
 - phpunit -c phpunit.xml
 - php vendor/bin/coveralls -v
